- presentation/src/main/java/com/kusitms/presentation/ui/signIn/SignInScreen2.kt
- presentation/src/main/res/drawable/screen2_photo.xml
- presentation/src/main/res/values/strings.xml
**SignInScreen**
-------------------------------------------------
> #2 SignInScreen2

- presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/SignIn2Vector.kt
- presentation/src/main/java/com/kusitms/presentation/ui/signIn/SignInScreen2.kt
- presentation/src/main/res/drawable/ic_plus.xml
**SignInScreen**
-------------------------------------------------
> SignInScreen2/Vector Folder Rename

- presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/SignIn2Vector.kt
- presentation/src/main/java/com/kusitms/presentation/ui/signIn/SignInScreen2.kt
**SignInScreen2**
---------------------------
변경사항
trashcan : compose Function -> ImageVector
textfield : 보이지 않는 오류 해결 진행중
> SignInscreen2

- presentation/src/main/java/com/kusitms/presentation/ui/signIn/SignInScreen2.kt
**SignInScreen2**
--------------------------------
전체 화면 간격 조정
> Fix: Spacer value

- presentation/src/main/java/com/kusitms/presentation/ui/signIn/KusitmsInputField.kt
- presentation/src/main/java/com/kusitms/presentation/ui/signIn/LinkCheckBox.kt
- presentation/src/main/java/com/kusitms/presentation/ui/signIn/SignInScreen2.kt
- presentation/src/main/res/drawable/ic_inputx.xml
- presentation/src/main/res/values/strings.xml
LinkCheckRow 
LinkCheckInputField
LinkCheckBox
> LinkCheckRow Class화

- presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
**Navigation Animation** 
-----------------------------------------
화면에 진입할때 -> 왼쪽으로 넘어가는 애니메이션
화면에서 나갈때 -> 오른쪽으로 넘어는 애니메이션
---------------------------------------
문제
1. 계속해서 반복되는 코드로 작성할 경우 길어질것 같아서 따로 함수로 빼고 싶은데 lamda parameter를 사용할 수 없다거나, 해당 함수는 composable에서만 사용할 수 있다는 오류 발생
> Add: Navigation Animation

- presentation/src/main/java/com/kusitms/presentation/ui/login/nonMember/NonMemberScreen.kt
> Remove: 공백 제거 & Branch Closed

- presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsMarginSpacer.kt
- presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsTab.kt
- presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsTopBar.kt
- presentation/src/main/java/com/kusitms/presentation/model/notice/NoticeUiModel.kt
- presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
- presentation/src/main/java/com/kusitms/presentation/navigation/NavRoutes.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/NoticeList.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/NoticeScreen.kt
- presentation/src/main/java/com/kusitms/presentation/ui/signIn/SignInProfileComplete.kt
- 공지사항 화면 추가 (NoticeScreen)
- 공지사항 화면 상단바 추가
- KusitsmTopBar 추가
- 공지사항,커리큘럼 탭 추가
- KusitmsTab : Tab Composable 추가
- 커리큘럼 화면은 아직 미완성
- 공지사항 탭 클릭 시 나타나는 공지사항 리스트 추가
- SignInProfileComplete - 시작하기 버튼 클릭 시 NoticeScreen으로 이동하게 수정
* 아이콘은 아직 추가하지 않아서, Spacer로 색깔있는 빈공간으로 채워두었습니다.
> Add 공지사항 화면 추가 - 공지사항 탭 화면 UI

- presentation/src/main/java/com/kusitms/presentation/common/ui/KusitsmButton.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/NoticeList.kt
- 최상단 스크롤 버튼 추가
- 안읽은 공지 보기 처리
- 빈리스트 대응(gif에서는 보이지 않습니다)
> Mod: NoticeList - 최상단 스크롤 버튼 추가, 안읽은 공지 보기 처리, 빈리스트 대응

- presentation/src/main/java/com/kusitms/presentation/model/notice/CurriculumUiModel.kt
- presentation/src/main/java/com/kusitms/presentation/model/notice/NoticeUiModel.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/CurriculumList.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/NoticeScreen.kt
- 커리큘럼 탭 화면 UI 작업
- 커리큘럼 별 내부 공지사항 목록 구현
- 내부 공지사항의 타이틀에 해당하는 데이터 관해 논의 필요
<br/>
> Add 커리큘럽 탭 화면 UI

- presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsDialog.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailScreen.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/comment/NoticeComment.kt
- 공지사항 더보기 Bottom Sheet 추가
- 댓글 신고하기 Bottom Sheet 추가
- 다이얼로그 component 추가
> Add 공지사항 더보기, 신고

- data/src/main/java/com/kusitms/data/NoticeRepositoryImpl.kt
- data/src/main/java/com/kusitms/data/remote/api/KusitmsApi.kt
- data/src/main/java/com/kusitms/data/remote/entity/response/notice/NoticePayload.kt
- domain/src/main/java/com/kusitms/domain/model/notice/NoticeModel.kt
- domain/src/main/java/com/kusitms/domain/repository/NoticeRepository.kt
- domain/src/main/java/com/kusitms/domain/usecase/notice/DeleteCommentUseCase.kt
- domain/src/main/java/com/kusitms/domain/usecase/notice/GetCurriculumListUseCase.kt
- domain/src/main/java/com/kusitms/domain/usecase/notice/GetCurriculumNoticeListUseCase.kt
- domain/src/main/java/com/kusitms/domain/usecase/notice/GetNoticeCommentListUseCase.kt
- domain/src/main/java/com/kusitms/domain/usecase/notice/GetNoticeDetailUseCase.kt
- domain/src/main/java/com/kusitms/domain/usecase/notice/GetNoticeListUseCase.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/CurriculumListScreen.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/NoticeListScreen.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/NoticeScreen.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailScreen.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/comment/NoticeComment.kt
이슈 번호 : #57
댓글 삭제, 커리큘럼 공지사항 연동, 댓글 입력 글자수 제한, 현재 사용하지 않는 기능 히든처리, 커리큘럼 공지 클릭 시 공지 상세 이동
```kotlin
```
```
ex)
```
> [FEAT] 댓글 삭제, 커리큘럼 공지사항 연동 및 etc

- data/src/main/java/com/kusitms/data/local/AuthDataStore.kt
- data/src/main/java/com/kusitms/data/remote/api/KusitmsApi.kt
- data/src/main/java/com/kusitms/data/remote/api/KusitmsTokenApi.kt
- data/src/main/java/com/kusitms/data/remote/di/AuthTokenInterceptor.kt
- data/src/main/java/com/kusitms/data/remote/di/NetworkModule.kt
- data/src/main/java/com/kusitms/data/remote/di/RepositoryModule.kt
- data/src/main/java/com/kusitms/data/remote/di/TokenManager.kt
- data/src/main/java/com/kusitms/data/repository/LoginRepositoryImpl.kt
- data/src/main/java/com/kusitms/data/repository/SignInRepositoryImpl.kt
- domain/src/main/java/com/kusitms/domain/repository/LoginRepository.kt
- presentation/src/main/java/com/kusitms/presentation/model/login/findPw/FindPwViewModel.kt
- presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwCodeValidation.kt
- presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/component/FindPw2Input.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/NoticeViewModel.kt
이슈 번호 : #번호
한 줄 요약
```kotlin
```
```
ex)
```
> FEAT: REFRESH토큰

- data/src/main/java/com/kusitms/data/remote/api/KusitmsApi.kt
- data/src/main/java/com/kusitms/data/remote/di/RepositoryModule.kt
- data/src/main/java/com/kusitms/data/remote/entity/response/CheckPasswordPayload.kt
- data/src/main/java/com/kusitms/data/repository/ChangePwRepositoryImpl.kt
- domain/src/main/java/com/kusitms/domain/repository/ChangePwRepository.kt
- domain/src/main/java/com/kusitms/domain/usecase/changepw/CheckPasswordUseCase.kt
- domain/src/main/java/com/kusitms/domain/usecase/changepw/UpdatePasswordAsLoggedInUseCase.kt
- presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsInputField.kt
- presentation/src/main/java/com/kusitms/presentation/model/login/findPw/FindPwViewModel.kt
- presentation/src/main/java/com/kusitms/presentation/model/login/findPw/UpdatePwViewModel.kt
- presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
- presentation/src/main/java/com/kusitms/presentation/navigation/NavRoutes.kt
- presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwCheckEmail.kt
- presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwCodeValidation.kt
- presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwMemberCurrent.kt
- presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwSetNewPw.kt
- presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/component/FindPwSetPwInput.kt
이슈 번호 : #65 
비밀번호 확인 및 변경 API 및 화면 연동, 일부 로직 수정
```kotlin
```
```
ex)
```
> [FEAT] 비밀번호 확인 및 변경

- domain/src/main/java/com/kusitms/domain/usecase/signin/MemberLogOutUseCase.kt
- presentation/src/main/java/com/kusitms/presentation/model/setting/SettingUiModel.kt
- presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
- presentation/src/main/java/com/kusitms/presentation/ui/login/findPw/FindPwSetNewPw.kt
- presentation/src/main/java/com/kusitms/presentation/ui/setting/SettingMember.kt
- presentation/src/main/java/com/kusitms/presentation/ui/signIn/SignInProfileComplete.kt
- presentation/src/main/res/values/strings.xml
이슈 번호 : #56 
회원탈퇴와 로그아웃이 뒤바뀌어있었던 상황..
수정했습니다
> [FIX]: 로그아웃 <-> 회원탈퇴 수정 

- presentation/src/main/java/com/kusitms/presentation/common/ui/KusitmsBottomNavigationBar.kt
- presentation/src/main/java/com/kusitms/presentation/common/util/NavUtil.kt
- presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
- presentation/src/main/java/com/kusitms/presentation/navigation/TopLevelDestination.kt
- presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/__KusitmsIcons.kt
- presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/kusitmsicons/BottomNavAttendance.kt
- presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/kusitmsicons/BottomNavHome.kt
- presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/kusitmsicons/BottomNavNotice.kt
- presentation/src/main/java/com/kusitms/presentation/ui/ImageVector/icons/kusitmsicons/BottomNavProfile.kt
- presentation/src/main/java/com/kusitms/presentation/ui/login/member/LoginMemberScreen.kt
- presentation/src/main/java/com/kusitms/presentation/ui/splash/SplashScreen.kt
- presentation/src/main/res/values/strings.xml
이슈 번호 : #79 
BottomNavigationBar 추가
```kotlin
```
```
ex)
```
> [FEAT] : 하단바 구현

- data/src/main/java/com/kusitms/data/NoticeRepositoryImpl.kt
- data/src/main/java/com/kusitms/data/remote/api/KusitmsApi.kt
- data/src/main/java/com/kusitms/data/remote/di/RepositoryModule.kt
- data/src/main/java/com/kusitms/data/remote/entity/response/notice/NoticePayload.kt
- data/src/main/java/com/kusitms/data/repository/NoticeRepositoryImpl.kt
- domain/src/main/java/com/kusitms/domain/model/notice/NoticeModel.kt
- domain/src/main/java/com/kusitms/domain/repository/NoticeRepository.kt
- domain/src/main/java/com/kusitms/domain/usecase/notice/GetChildCommentListUseCase.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailBottomSheet.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailScreen.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailViewModel.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/comment/NoticeComment.kt
이슈 번호 : #77 
공지 대댓글 UI 및 대댓글 목록 조회
- 공지사항 목록 조회, 상세 조회 v2로 변경(페이징 적용은 아직 x)
- 대댓글 BottomSheet 추가 및 대댓글 목록 조회 API 연동
*대댓글 입력과 대댓글 신고,삭제는 다음 작업에 진행하겠습니다.
```kotlin
```
```
ex)
```
> [FEAT] 공지 대댓글 UI 및 대댓글 목록 조회

- data/src/main/java/com/kusitms/data/remote/api/KusitmsApi.kt
- data/src/main/java/com/kusitms/data/remote/entity/response/notice/NoticePayload.kt
- domain/src/main/java/com/kusitms/domain/model/notice/NoticeModel.kt
- presentation/src/main/java/com/kusitms/presentation/navigation/NavGraph.kt
- presentation/src/main/java/com/kusitms/presentation/navigation/NavRoutes.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/NoticeListScreen.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/NoticeScreen.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailScreen.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/search/NoticeSearchScreen.kt
- presentation/src/main/java/com/kusitms/presentation/ui/viewer/ImageViewerScreen.kt
- presentation/src/main/res/values/strings.xml
이슈 번호 : #77 
공지 검색 화면 추가 및 구현
```kotlin
```
```
ex)
```
> [FEAT] 공지 검색 화면

- presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailBottomSheet.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailScreen.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailViewModel.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/comment/NoticeComment.kt
이슈 번호 : #77
공지 대댓글 추가 및 삭제 시 갱신되지 않는 문제 수정
```kotlin
```
```
ex)
```
> [FEAT] 공지 대댓글 추가 및 삭제 시 갱신되지 않는 문제 수정

- presentation/src/main/java/com/kusitms/presentation/model/profile/PartList.kt
- presentation/src/main/java/com/kusitms/presentation/model/profile/ProfileViewModel.kt
- presentation/src/main/java/com/kusitms/presentation/ui/profile/ProfileItem.kt
- presentation/src/main/res/values/strings.xml
이슈 번호 : #96
프로필 리스트에서 프로필 한 줄 소개 2줄까지만  표시
파트 선택 -> 전체로 텍스트를 변경했고 전체 프로필 조회 필터링을 구현하였습니다.
```kotlin
```
```
ex)
```
> [FEAT] 프로필 VIEW 피그마 변경 사항 반영

- data/src/main/java/com/kusitms/data/remote/entity/response/notice/NoticeVotePayload.kt
- domain/src/main/java/com/kusitms/domain/model/notice/NoticeVoteModel.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/NoticeDetailViewModel.kt
- presentation/src/main/java/com/kusitms/presentation/ui/notice/detail/vote/NoticeVote.kt
- presentation/src/main/res/values/strings.xml
이슈 번호 : #77
다시 투표하기 추가하였습니다.
** 투표 종료를 어떻게 판단하는지?, 이미 투표했는데 다른 항목을 투표하면 이전에 투표한게 사라지지 않아서 복수투표가 되어버리는 상황이 되어서 논의가 필요할 것 같습니다.
```kotlin
```
```
ex)
```
> [FEAT] 다시 투표하기 추가
